import numpy as np
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt

# This file was generated by Claude.ai

def generate_gmm_samples(n_samples, k_components, dim=1, mean_range=(-5, 5), var_range=(0.5, 3.0), random_state=None):
    """
    Generate N samples from a Gaussian mixture model with k components.
    
    Parameters:
    -----------
    n_samples : int
        Number of samples to generate
    k_components : int
        Number of mixture components
    dim : int, default=1
        Dimensionality of the data (1D or 2D supported)
    mean_range : tuple, default=(-5, 5)
        Range for randomly generating component means
    var_range : tuple, default=(0.5, 3.0)
        Range for randomly generating component variances
    random_state : int, optional
        Random seed for reproducibility
        
    Returns:
    --------
    samples : ndarray of shape (n_samples, dim)
        Generated samples
    params : dict
        Dictionary containing the true parameters:
        - 'means': component means
        - 'covariances': component covariances
        - 'weights': mixture weights
        - 'component_labels': which component each sample came from
    """
    if random_state is not None:
        np.random.seed(random_state)
    
    # Generate random mixture weights (ensuring each is >= 0.1)
    # First, generate k random numbers
    raw_weights = np.random.uniform(0.1, 1.0, k_components)
    # Normalize to sum to 1
    weights = raw_weights / np.sum(raw_weights)
    
    # Ensure minimum weight constraint
    while np.any(weights < 0.1):
        # If any weight is below 0.1, regenerate
        raw_weights = np.random.uniform(0.1, 1.0, k_components)
        weights = raw_weights / np.sum(raw_weights)
    
    # Generate random means for each component
    if dim == 1:
        means = np.random.uniform(mean_range[0], mean_range[1], k_components)
        # Generate random variances (diagonal covariance matrices for simplicity)
        variances = np.random.uniform(var_range[0], var_range[1], k_components)
        covariances = variances  # For 1D, covariance is just variance
    else:
        means = np.random.uniform(mean_range[0], mean_range[1], (k_components, dim))
        # Generate random covariance matrices (diagonal for simplicity)
        variances = np.random.uniform(var_range[0], var_range[1], (k_components, dim))
        covariances = np.array([np.diag(var) for var in variances])
    
    # Determine how many samples to draw from each component
    component_counts = np.random.multinomial(n_samples, weights)
    
    # Generate samples
    samples = []
    component_labels = []
    
    for i in range(k_components):
        n_comp_samples = component_counts[i]
        if n_comp_samples > 0:
            if dim == 1:
                comp_samples = np.random.normal(means[i], np.sqrt(covariances[i]), n_comp_samples)
                samples.extend(comp_samples)
            else:
                comp_samples = multivariate_normal.rvs(
                    mean=means[i], 
                    cov=covariances[i], 
                    size=n_comp_samples
                )
                if n_comp_samples == 1:
                    comp_samples = comp_samples.reshape(1, -1)
                samples.extend(comp_samples)
            
            component_labels.extend([i] * n_comp_samples)
    
    # Convert to numpy arrays
    samples = np.array(samples)
    if dim == 1:
        samples = samples.reshape(-1, 1)
    component_labels = np.array(component_labels)
    
    # Shuffle the samples (since we generated them component by component)
    shuffle_idx = np.random.permutation(len(samples))
    samples = samples[shuffle_idx]
    component_labels = component_labels[shuffle_idx]
    
    # Package parameters
    params = {
        'means': means,
        'covariances': covariances,
        'weights': weights,
        'component_labels': component_labels
    }
    
    return samples, params

def plot_gmm_samples(samples, params, axes=None, title="GMM Samples"):
    """
    Utility function to plot the generated samples (works for 1D and 2D).
    
    Parameters:
    -----------
    samples : ndarray
        Generated samples from GMM
    params : dict
        Parameters dictionary from generate_gmm_samples
    axes : matplotlib.axes.Axes, optional
        Matplotlib axes to plot on. If None, creates new figure
    title : str, default="GMM Samples"
        Title for the plot
        
    Returns:
    --------
    axes : matplotlib.axes.Axes
        The axes object with the plot
    """
    dim = samples.shape[1]
    component_labels = params['component_labels']
    
    if axes is None:
        fig, axes = plt.subplots(figsize=(10, 6))
    
    if dim == 1:
        # 1D plot: histogram
        axes.hist(samples[:, 0], bins=25)
        
        axes.set_xlabel('Value')
        axes.set_ylabel('Frequency')
        axes.legend()
        
    elif dim == 2:
        # 2D scatter plot
        unique_labels = np.unique(component_labels)
        colors = plt.cm.Set3(np.linspace(0, 1, len(unique_labels)))
        
        for i, label in enumerate(unique_labels):
            mask = component_labels == label
            axes.scatter(samples[mask, 0], samples[mask, 1], 
                        alpha=0.6, label=f'Component {label}', color=colors[i])
        
        axes.set_xlabel('X1')
        axes.set_ylabel('X2')
        axes.legend()
    
    axes.set_title(title)
    axes.grid(True, alpha=0.3)
    
    return axes

# Example usage
if __name__ == "__main__":
    # Generate 1D samples
    print("1D Gaussian Mixture Model Example:")
    samples_1d, params_1d = generate_gmm_samples(
        n_samples=1000, 
        k_components=3, 
        dim=1,
        random_state=42
    )
    
    print(f"Generated {len(samples_1d)} samples from {len(params_1d['weights'])} components")
    print(f"Mixture weights: {params_1d['weights']}")
    print(f"Component means: {params_1d['means']}")
    print(f"Component variances: {params_1d['covariances']}")
    
    # Plot 1D samples
    fig, ax = plt.subplots(figsize=(10, 6))
    plot_gmm_samples(samples_1d, params_1d, axes=ax, title="1D GMM Samples")
    plt.show()
    
    print("\n" + "="*50 + "\n")
    
    # Generate 2D samples
    print("2D Gaussian Mixture Model Example:")
    samples_2d, params_2d = generate_gmm_samples(
        n_samples=500, 
        k_components=4, 
        dim=2,
        random_state=123
    )
    
    print(f"Generated {len(samples_2d)} samples from {len(params_2d['weights'])} components")
    print(f"Mixture weights: {params_2d['weights']}")
    print(f"Component means:\n{params_2d['means']}")
    
    # Plot 2D samples
    fig, ax = plt.subplots(figsize=(10, 6))
    plot_gmm_samples(samples_2d, params_2d, axes=ax, title="2D GMM Samples")
    plt.show()